# Site settings
title: Data-ScicenceR
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 The website provides several materials for an actuary to set up his/her everyday workflow.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  datasciencer

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
